//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffold {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scaffold.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignBottom32 {
            get {
                object obj = ResourceManager.GetObject("AlignBottom32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignBottomGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignBottomGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignCenter32 {
            get {
                object obj = ResourceManager.GetObject("AlignCenter32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignCenterGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignCenterGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignLeft32 {
            get {
                object obj = ResourceManager.GetObject("AlignLeft32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignLeftGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignLeftGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignMiddle32 {
            get {
                object obj = ResourceManager.GetObject("AlignMiddle32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignMiddleGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignMiddleGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignRight32 {
            get {
                object obj = ResourceManager.GetObject("AlignRight32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignRightGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignRightGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignTop32 {
            get {
                object obj = ResourceManager.GetObject("AlignTop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignTopGray32 {
            get {
                object obj = ResourceManager.GetObject("AlignTopGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlphaCheckerLarge {
            get {
                object obj = ResourceManager.GetObject("AlphaCheckerLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Audio128 {
            get {
                object obj = ResourceManager.GetObject("Audio128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Audio32 {
            get {
                object obj = ResourceManager.GetObject("Audio32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CaptionLeft {
            get {
                object obj = ResourceManager.GetObject("CaptionLeft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CaptionRight {
            get {
                object obj = ResourceManager.GetObject("CaptionRight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #333333.
        /// </summary>
        internal static string colorBackground {
            get {
                return ResourceManager.GetString("colorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #204060.
        /// </summary>
        internal static string colorBackgroundActive {
            get {
                return ResourceManager.GetString("colorBackgroundActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #606060.
        /// </summary>
        internal static string colorBackgroundHighlight {
            get {
                return ResourceManager.GetString("colorBackgroundHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string colorBackgroundWriting {
            get {
                return ResourceManager.GetString("colorBackgroundWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e0e0e0.
        /// </summary>
        internal static string colorBackgroundWritingDisabled {
            get {
                return ResourceManager.GetString("colorBackgroundWritingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffc3cc.
        /// </summary>
        internal static string colorBackgroundWritingError {
            get {
                return ResourceManager.GetString("colorBackgroundWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #999999.
        /// </summary>
        internal static string colorTextDisabled {
            get {
                return ResourceManager.GetString("colorTextDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #dcdcdc.
        /// </summary>
        internal static string colorTextNormal {
            get {
                return ResourceManager.GetString("colorTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        internal static string colorTextWriting {
            get {
                return ResourceManager.GetString("colorTextWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #999999.
        /// </summary>
        internal static string colorTextWritingDisabled {
            get {
                return ResourceManager.GetString("colorTextWritingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #404040.
        /// </summary>
        internal static string colorTitleBackgroundNormal {
            get {
                return ResourceManager.GetString("colorTitleBackgroundNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f5f5f5.
        /// </summary>
        internal static string colorTitleTextActive {
            get {
                return ResourceManager.GetString("colorTitleTextActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #a9a9a9.
        /// </summary>
        internal static string colorTitleTextInactive {
            get {
                return ResourceManager.GetString("colorTitleTextInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e91122.
        /// </summary>
        internal static string colorWinControlClose {
            get {
                return ResourceManager.GetString("colorWinControlClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #606060.
        /// </summary>
        internal static string colorWinControlHover {
            get {
                return ResourceManager.GetString("colorWinControlHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #404040.
        /// </summary>
        internal static string colorWinControlNormal {
            get {
                return ResourceManager.GetString("colorWinControlNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DistributeHorz32 {
            get {
                object obj = ResourceManager.GetObject("DistributeHorz32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DistributeHorzGray32 {
            get {
                object obj = ResourceManager.GetObject("DistributeHorzGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DistributeVert32 {
            get {
                object obj = ResourceManager.GetObject("DistributeVert32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DistributeVertGray32 {
            get {
                object obj = ResourceManager.GetObject("DistributeVertGray32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolCircle {
            get {
                object obj = ResourceManager.GetObject("DrawToolCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolCursor {
            get {
                object obj = ResourceManager.GetObject("DrawToolCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolLine {
            get {
                object obj = ResourceManager.GetObject("DrawToolLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolPolyline {
            get {
                object obj = ResourceManager.GetObject("DrawToolPolyline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolRectangle {
            get {
                object obj = ResourceManager.GetObject("DrawToolRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrawToolText {
            get {
                object obj = ResourceManager.GetObject("DrawToolText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filmstrip32 {
            get {
                object obj = ResourceManager.GetObject("Filmstrip32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilmstripArrow32 {
            get {
                object obj = ResourceManager.GetObject("FilmstripArrow32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilmstripTrash32 {
            get {
                object obj = ResourceManager.GetObject("FilmstripTrash32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string htmlBlankLine {
            get {
                return ResourceManager.GetString("htmlBlankLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///		!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlDefault {
            get {
                return ResourceManager.GetString("htmlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;.
        /// </summary>
        internal static string htmlHeaderBasic {
            get {
                return ResourceManager.GetString("htmlHeaderBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///		/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///		!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undefined&quot;!=typeof window?window:this,function(C,e){&quot;use strict&quot;;var t=[],E=C.document,r=Object.getPrototypeOf,s=t.slice,g=t.concat,u=t.push,i=t.indexOf,n={},o=n.t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmljQueryEmbedded {
            get {
                return ResourceManager.GetString("htmljQueryEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///		!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlSVGInteractive {
            get {
                return ResourceManager.GetString("htmlSVGInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Link128 {
            get {
                object obj = ResourceManager.GetObject("Link128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Link32 {
            get {
                object obj = ResourceManager.GetObject("Link32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoAutoShape32 {
            get {
                object obj = ResourceManager.GetObject("msoAutoShape32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoCallout32 {
            get {
                object obj = ResourceManager.GetObject("msoCallout32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoCanvas32 {
            get {
                object obj = ResourceManager.GetObject("msoCanvas32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoChart32 {
            get {
                object obj = ResourceManager.GetObject("msoChart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoComment32 {
            get {
                object obj = ResourceManager.GetObject("msoComment32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoContentApp32 {
            get {
                object obj = ResourceManager.GetObject("msoContentApp32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoDiagram32 {
            get {
                object obj = ResourceManager.GetObject("msoDiagram32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoEmbeddedOLEObject32 {
            get {
                object obj = ResourceManager.GetObject("msoEmbeddedOLEObject32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoFormControl32 {
            get {
                object obj = ResourceManager.GetObject("msoFormControl32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoFreeform32 {
            get {
                object obj = ResourceManager.GetObject("msoFreeform32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoGroup32 {
            get {
                object obj = ResourceManager.GetObject("msoGroup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoInk32 {
            get {
                object obj = ResourceManager.GetObject("msoInk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoInkComment32 {
            get {
                object obj = ResourceManager.GetObject("msoInkComment32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoLinkedOLEObject32 {
            get {
                object obj = ResourceManager.GetObject("msoLinkedOLEObject32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoLinkedPicture32 {
            get {
                object obj = ResourceManager.GetObject("msoLinkedPicture32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoMedia32 {
            get {
                object obj = ResourceManager.GetObject("msoMedia32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoOLEControlObject32 {
            get {
                object obj = ResourceManager.GetObject("msoOLEControlObject32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoPicture32 {
            get {
                object obj = ResourceManager.GetObject("msoPicture32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoPlaceholder32 {
            get {
                object obj = ResourceManager.GetObject("msoPlaceholder32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoScriptAnchor32 {
            get {
                object obj = ResourceManager.GetObject("msoScriptAnchor32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoShapeTypeMixed32 {
            get {
                object obj = ResourceManager.GetObject("msoShapeTypeMixed32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoSlicer32 {
            get {
                object obj = ResourceManager.GetObject("msoSlicer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoSmartArt32 {
            get {
                object obj = ResourceManager.GetObject("msoSmartArt32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoTable32 {
            get {
                object obj = ResourceManager.GetObject("msoTable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoTextBox32 {
            get {
                object obj = ResourceManager.GetObject("msoTextBox32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoTextEffect32 {
            get {
                object obj = ResourceManager.GetObject("msoTextEffect32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoWebVideo32 {
            get {
                object obj = ResourceManager.GetObject("msoWebVideo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeDelay {
            get {
                object obj = ResourceManager.GetObject("NodeDelay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeDelayHighlight {
            get {
                object obj = ResourceManager.GetObject("NodeDelayHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeFork {
            get {
                object obj = ResourceManager.GetObject("NodeFork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeForkHighlight {
            get {
                object obj = ResourceManager.GetObject("NodeForkHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeStart {
            get {
                object obj = ResourceManager.GetObject("NodeStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeStartHighlight {
            get {
                object obj = ResourceManager.GetObject("NodeStartHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeTermination {
            get {
                object obj = ResourceManager.GetObject("NodeTermination", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NodeTerminationHighlight {
            get {
                object obj = ResourceManager.GetObject("NodeTerminationHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pinpoint {
            get {
                object obj = ResourceManager.GetObject("Pinpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;command&gt;[^\(]+)\((?&lt;params&gt;[^\)]*)\)).
        /// </summary>
        internal static string rxCommandParams {
            get {
                return ResourceManager.GetString("rxCommandParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:(?&lt;filenameextension&gt;(?&lt;filename&gt;[^\\/\?]+)(?!.*(\\|/))\.(?&lt;extension&gt;[^\\/\?]+))(?&lt;parameters&gt;\?.*){0,1})).
        /// </summary>
        internal static string rxFilenameInPath {
            get {
                return ResourceManager.GetString("rxFilenameInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \{(?&lt;name&gt;[^\:\}]+)(\:(?&lt;format&gt;[^\}]*)){0,1}\}.
        /// </summary>
        internal static string rxFormatString {
            get {
                return ResourceManager.GetString("rxFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:(?&lt;n&gt;[^ \&lt;\&gt;\s\r\n/=]+)(\s*=\s*\&quot;(?&lt;v&gt;[^\&quot;]*)\&quot;){0,1})).
        /// </summary>
        internal static string rxHTMLElement {
            get {
                return ResourceManager.GetString("rxHTMLElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;g&gt;^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$)).
        /// </summary>
        internal static string rxIsGUID {
            get {
                return ResourceManager.GetString("rxIsGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:^\s*\[)).
        /// </summary>
        internal static string rxJSONStartArray {
            get {
                return ResourceManager.GetString("rxJSONStartArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:^\s*\{)).
        /// </summary>
        internal static string rxJSONStartObject {
            get {
                return ResourceManager.GetString("rxJSONStartObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;pattern&gt;-{0,1}[0-9]+(\.[0-9]+){0,1}(e-{0,1}[0-9]+){0,1})).
        /// </summary>
        internal static string rxNumeric {
            get {
                return ResourceManager.GetString("rxNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:(?&lt;outer&gt;xlink\:href\s*=\s*\&quot;(?!(\#|data\:))(?&lt;inner&gt;[^\&quot;]+)\&quot;))).
        /// </summary>
        internal static string rxSVGHREFFind {
            get {
                return ResourceManager.GetString("rxSVGHREFFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;line&gt;[^\r\n]+)\s*(\r|\n|$)\s*.
        /// </summary>
        internal static string rxTextLine {
            get {
                return ResourceManager.GetString("rxTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ScaffoldIcon {
            get {
                object obj = ResourceManager.GetObject("ScaffoldIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScaffoldIcon24 {
            get {
                object obj = ResourceManager.GetObject("ScaffoldIcon24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Socket {
            get {
                object obj = ResourceManager.GetObject("Socket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransportBack32 {
            get {
                object obj = ResourceManager.GetObject("TransportBack32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransportNext32 {
            get {
                object obj = ResourceManager.GetObject("TransportNext32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransportPause32 {
            get {
                object obj = ResourceManager.GetObject("TransportPause32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransportPlay32 {
            get {
                object obj = ResourceManager.GetObject("TransportPlay32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransportStop32 {
            get {
                object obj = ResourceManager.GetObject("TransportStop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VSliderHandleL {
            get {
                object obj = ResourceManager.GetObject("VSliderHandleL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VSliderHandleR {
            get {
                object obj = ResourceManager.GetObject("VSliderHandleR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlH0 {
            get {
                object obj = ResourceManager.GetObject("WinControlH0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlH1 {
            get {
                object obj = ResourceManager.GetObject("WinControlH1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlM0 {
            get {
                object obj = ResourceManager.GetObject("WinControlM0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlM1 {
            get {
                object obj = ResourceManager.GetObject("WinControlM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlN0 {
            get {
                object obj = ResourceManager.GetObject("WinControlN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlN1 {
            get {
                object obj = ResourceManager.GetObject("WinControlN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlX0 {
            get {
                object obj = ResourceManager.GetObject("WinControlX0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinControlX1 {
            get {
                object obj = ResourceManager.GetObject("WinControlX1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
